paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carts
      responses:
        '201':
          description: Carrito creado con éxito
    get:
      summary: Obtener todos los carritos
      tags:
        - Carts
      responses:
        '200':
          description: Éxito

  '/api/carts/{cId}/product/{pid}':
    post:
      summary: Agregar un producto a un carrito
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto agregado con éxito
    delete:
      summary: Eliminar un producto de un carrito
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado con éxito

  '/api/carts/{cId}':
    get:
      summary: Obtener un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Éxito
    put:
      summary: Actualizar un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito actualizado con éxito
    delete:
      summary: Eliminar un carrito por ID
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Carrito eliminado con éxito

  '/api/carts/{cId}/products/{pid}':
    delete:
      summary: Eliminar todos los productos de un carrito
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Todos los productos eliminados con éxito

  '/api/carts/{cId}/purchase':
    post:
      summary: Realizar una compra con un carrito
      tags:
        - Carts
      parameters:
        - in: path
          name: cId
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        '200':
          description: Compra realizada con éxito